[32m2022-01-06 14:21:47.569[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m43[0m - [32m[1mSSH客户端创建成功.[0m
[32m2022-01-06 14:21:48.737[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m47[0m - [32m[1mSFTP客户端创建成功.[0m
[32m2022-01-06 14:21:48.762[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: mkdir backup_sql -> 输出结果: [0m
[32m2022-01-06 14:21:48.762[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: [0m
[32m2022-01-06 14:21:48.812[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: docker exec -i mysql8 mysqldump -h127.0.0.1 -uroot -ppassword apiautotest > /root/backup_sql/apiautotest_2022-01-06T14_21_46.sql -> 输出结果: [0m
[32m2022-01-06 14:21:48.812[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: bash: docker: command not found
[0m
[32m2022-01-06 14:21:50.074[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m43[0m - [32m[1mSSH客户端创建成功.[0m
[32m2022-01-06 14:21:51.491[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m47[0m - [32m[1mSFTP客户端创建成功.[0m
[32m2022-01-06 14:21:51.498[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: mkdir backup_sql -> 输出结果: [0m
[32m2022-01-06 14:21:51.498[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: mkdir: cannot create directory ‘backup_sql’: File exists
[0m
[32m2022-01-06 14:21:51.545[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: docker exec -i mysql8 mysqldump -h127.0.0.1 -uroot -ppassword apiautotest > /root/backup_sql/apiautotest_2022-01-06T14_21_46.sql -> 输出结果: [0m
[32m2022-01-06 14:21:51.545[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: bash: docker: command not found
[0m
[32m2022-01-06 14:21:52.681[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m43[0m - [32m[1mSSH客户端创建成功.[0m
[32m2022-01-06 14:21:53.843[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m47[0m - [32m[1mSFTP客户端创建成功.[0m
[32m2022-01-06 14:21:53.848[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: mkdir backup_sql -> 输出结果: [0m
[32m2022-01-06 14:21:53.848[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: mkdir: cannot create directory ‘backup_sql’: File exists
[0m
[32m2022-01-06 14:21:53.897[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: docker exec -i mysql8 mysqldump -h127.0.0.1 -uroot -ppassword apiautotest > /root/backup_sql/apiautotest_2022-01-06T14_21_46.sql -> 输出结果: [0m
[32m2022-01-06 14:21:53.897[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: bash: docker: command not found
[0m
