[32m2022-01-06 14:24:03.756[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m43[0m - [32m[1mSSH客户端创建成功.[0m
[32m2022-01-06 14:24:04.609[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m47[0m - [32m[1mSFTP客户端创建成功.[0m
[32m2022-01-06 14:24:04.615[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: mkdir backup_sql -> 输出结果: [0m
[32m2022-01-06 14:24:04.615[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: mkdir: cannot create directory ‘backup_sql’: File exists
[0m
[32m2022-01-06 14:24:04.663[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: docker exec -i mysql8 mysqldump -h127.0.0.1 -uroot -ppassword apiautotest > /root/backup_sql/apiautotest_2022-01-06T14_21_46.sql -> 输出结果: [0m
[32m2022-01-06 14:24:04.663[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: bash: docker: command not found
[0m
[32m2022-01-06 14:24:05.797[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m43[0m - [32m[1mSSH客户端创建成功.[0m
[32m2022-01-06 14:24:06.747[0m | [32m[1mSUCCESS [0m | [36mtools.data_clearing[0m:[36m__init__[0m:[36m47[0m - [32m[1mSFTP客户端创建成功.[0m
[32m2022-01-06 14:24:06.753[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: mkdir backup_sql -> 输出结果: [0m
[32m2022-01-06 14:24:06.753[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: mkdir: cannot create directory ‘backup_sql’: File exists
[0m
[32m2022-01-06 14:24:06.801[0m | [1mINFO    [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m55[0m - [1m输入命令: docker exec -i mysql8 mysqldump -h127.0.0.1 -uroot -ppassword apiautotest > /root/backup_sql/apiautotest_2022-01-06T14_21_46.sql -> 输出结果: [0m
[32m2022-01-06 14:24:06.802[0m | [31m[1mERROR   [0m | [36mtools.data_clearing[0m:[36mexecute_cmd[0m:[36m56[0m - [31m[1m异常信息: bash: docker: command not found
[0m
